name: build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Debug
          - build_type: Release

    env:
      EXTERNAL_ROOT: /home/runner/3party
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - uses: actions/checkout@v2

      - name: Install latest Boost
        shell: bash
        run: |
          sudo apt-add-repository ppa:mhier/libboost-latest
          sudo apt install libboost1.74-dev

      - name: Install dependencies from source
        run: .ci/fetch_system_dependencies.sh

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$EXTERNAL_ROOT

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

  build-docs:
    runs-on: ubuntu-latest
    #   Only build documentation for valid builds on master.
    needs: [build]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        shell: bash
        run: sudo apt install doxygen

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCONSOLEPP_DOC_ONLY=True

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target consolepp_doc

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{runner.workspace}}/build/html
